# Generated by Django 4.0.4 on 2022-05-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleted',
            name='from_name',
            field=models.CharField(default='nirbhay sharma', max_length=100),
        ),
        migrations.AddField(
            model_name='inbox',
            name='from_name',
            field=models.CharField(default='nirbhay sharma', max_length=100),
        ),
        migrations.AddField(
            model_name='sent',
            name='to_name',
            field=models.CharField(default='nirbhay sharma', max_length=100),
        ),
    ]
